### ISSUE TITLE
Firefox peer code review request

### ISSUE THREAD

**Issue by mlopatka** [mozilla/fingerprinting-blocking-methods-study-addon#14] opened 2019-12-03 15:39 UTC
This PR is not for merging, but as a placeholder for logging Firefox peer code review of this study.

**Comment by birdsarah** [comment] 2019-12-03 17:58
Some notes:
* control branch - simple pref monitoring and enrollment / unenrollment logic
* treatmentDomain - pref flipping and monitoring - has bug #13 that I'm working on day
* treatmentScript - simple pref monitoring and enrollment (identical to control) plus a stripped down version of ublock origin (https://github.com/gorhill/uBlock) to filter network requests based on a custom blockl list (/src/treatmentScript/assets/script_list.txt). The code that generates the list is in FPList folder.  Below I will post the differences with uBlock origin. The main goal of my modifications was to only include the code necessary to filter requests, while keeping modifications to a minimum, and to ensure that none of the other uBlock origin features creep in that may affect user experience in this case.

**Comment by birdsarah** [comment] 2019-12-03 19:59
Diff with ublock origin. This is compared to a compiled version of uBlock origin.

The main uBlock origin code compiles to 35 directories and 211 files (report from tree). From this, we only take code from lib, assets, and js.

For `lib` we take only the required libraries for the functionality we use - lz4 (compression), publicsuffix, and punycode.

From `assets` we take assets.json, and effective_tld_names.dat. In addition, we add script_list.txt which is our block list. assets.json is stripped down from a 600 line file to a 24 line file which just references the three files in the assets directory.

From `js` we take 29 out of the 80 files in the ublock code. 

Of the 29, we take the following un-changed:
* `wasm` - the wasm folder containing wasm implementations of the data structures biditrie and hntrie which are used to efficiently store and search the filter lists - this accounts for 5 files
* vapi-webrequest.js
* strie.js
* cachestorage.js
* uritools.js
* lz4.js
* hntrie.js
* text-encode.js
* vapi.js
* webext.js

We take and modify the following 15 files. In most cases, the modification is just removal of large chunks of unused code. The diff is here: https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb. Details:
* `LICENSE.md` the license is included and is modified to note that the code contains modifications.
* `assets.js` - [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L4-L338)
* `background.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L344-L427)
* `console.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L433-L473) - I do not believe this code is actually used, but I'm hesitant to remove in case of edge cases.
* `pagestore.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L478-L932) large removal of unused code. Add logging to browser console - particularly useful for QA verifying that desired blocking is happening.
* `start.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L935-L1114) removal of unused code
* `static-net-filtering.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L1120-L1754) large removal of unused code
* `tabs.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L1757-L2089) large removal of unused code
* `traffic.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L2089-L3046) large removal of unused code plus addition of a race condition bug I introduced somewhere by removing so much other code (#4).
* `ublock.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L3049-L3480) large removal of unused code
* `utils.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L3482-L3604) removal of unused code
* `vapi-background.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L3608-L4857) large removal of unused code
* `vapi-common.js` [diff](https://gist.github.com/birdsarah/02e03fea39d7d067c213e6b27e2cf1fb#file-ublock-treatmentscript-diff-L4862-L4913) removal of unused code

**Comment by birdsarah** [comment] 2019-12-03 22:21
Issue #13 is now fixed.

**Comment by rhelmer** [comment] 2019-12-04 04:49
Here is a new checklist we are trying for this sort of review (courtesy of @biancadanforth):

## Engineering Review Checklist for Firefox WebExtension Experiments
This is a working checklist for reviewing WebExtension experiments in Firefox. Items may be added, edited or removed at any time.

- [x] `README`:
  - [x] Explains clearly what the extension does for each experimental branch and control.
  - [x] Lists any extension configuration settings useful for testing.
  - [x] Links out to a META bug and/or other documents with more context, including what Firefox channel and version the experiment is targeted for.
- [x] `manifest.json` contains the following fields:
  - [x] `name`
  - [x] `version`
  - [x] `author`
  - [x] `description`
  - [x] `homepage_url`
  - ~~[ ] `icons` (`\"48\"` and `\"96\"`)~~
  - [x] `applications.gecko.id` (typically of the form `\"study-name@mozilla.org\"`)
  - [x] `applications.gecko.strict_min_version` (preferable)
  - ~~[ ] `applications.gecko.strict_max_version` (preferable)~~
- [x] WE API engineers confirm that the extension's use of WE APIs (public, privileged or experimental) will not trigger known bugs.
- [x] Extension [follows guidelines for modifying Firefox Prefs](https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#prefs).
~~- [ ] Extension [does not cause feature regressions in Try server tests](https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#testing-extensions).~~
- [x] Extension does not cause significant[1] performance regressions.
- [x] Only source files used by the extension are included in the XPI.
- [x] Additional reviews (e.g. data, legal, privacy, security, ...) may be required if:
~~- [ ] The extension makes use of third party libraries and/or services.~~
~~- [ ] Data is transmitted outside of Mozilla's telemetry pipeline~~
  - [x] The extension modifies web page content in any way.


[1]: As a reference, for a production application (i.e. not an experiment), a 2-3% worst case scenario regression in page load time would generally be considered acceptable. Since experiments are temporary and typically only go out to a very small percentage of users, we can often be more lenient.

**Comment by birdsarah** [comment] 2019-12-04 06:01
> Links out to a META bug and/or other documents with more context

Is META bug, the bugzilla bug or the experimenter?

> homepage_url

What is homepage url for study addon? This repo?

> icons

What icons should I use - where will they appear?

> WE API engineers confirm that the extension's use of WE APIs (public, privileged or experimental) will not trigger known bugs.

You will do this @rhelmer?

> Extension follows guidelines for modifying Firefox Prefs.

I followed previous code from @motin for pref flipping and handling (e.g. https://github.com/mozilla/federated-learning-v2-study-addon). I'm confused by the linked doc, it doesn't seem to use the prefs API that I was expecting e.g. `Services.prefs.getBoolPref`, `Services.prefs.setCharPref` can you point to the specific API (dxr link is fine) that you'd like me to use.

>  Extension does not cause feature regressions in Try server tests.

I understand from docs (which are great btw) that I "must have Level 1 commit access to use tryserver." (https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#example-extensions-testing-workflow) Is this something that I'm expected to run, or will QA run it? (cc @SoftVision-CosminMuntean )

> Extension does not cause significant[1] performance regressions.

1) I see: https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#testing-extensions step 2 - do I run this locally or does QA / something else run this on a standardized machine? 
2) Are there any other performance tests to run?

> Additional reviews 

* You scrubbed out "The extension makes use of third party libraries and/or services." but this code brings in code from ublock - just checking that we're good on this one
*  "The extension modifies web page content in any way." I believe we should be good on this. Although the treatmentScript branch modifies web page content it does so in a middle ground between current default - fingerprinting protection off, and current option - fingeprinting protection on which blocks at the whole domain level. The treatmentScript branch aims to only block fingerprinting scripts from fingerprinting domains. It has been restricted to only be content that would be blocked by flipping the fingerprinting pref.

**Comment by rhelmer** [comment] 2019-12-04 18:02
Thanks for being the guinea ping for this new checklist :) answers inline below:

> > Links out to a META bug and/or other documents with more context
> 
> Is META bug, the bugzilla bug or the experimenter?

I think experimenter is fine, anything you think would be helpful for other folks now and in the future to understand the experiment.

> 
> > homepage_url
> 
> What is homepage url for study addon? This repo?

Yes that is fine.

> 
> > icons
> 
> What icons should I use - where will they appear?

Studies don't appear in `about:addons` anymore and if you don't have icons exposed in Firefox (toolbar etc) then this probably isn't important. I don't think the icons appear in `about:studies`, @biancadanforth am I missing anything?

> 
> > WE API engineers confirm that the extension's use of WE APIs (public, privileged or experimental) will not trigger known bugs.
> 
> You will do this @rhelmer?
> 
> > Extension follows guidelines for modifying Firefox Prefs.

Yes.

> 
> I followed previous code from @motin for pref flipping and handling (e.g. https://github.com/mozilla/federated-learning-v2-study-addon). I'm confused by the linked doc, it doesn't seem to use the prefs API that I was expecting e.g. `Services.prefs.getBoolPref`, `Services.prefs.setCharPref` can you point to the specific API (dxr link is fine) that you'd like me to use.

This is done for you by @motin's pref-flipping API, I'll just take a look at that and double-check (we've used it before though so I expect it'll be fine).

> 
> > Extension does not cause feature regressions in Try server tests.
> 
> I understand from docs (which are great btw) that I "must have Level 1 commit access to use tryserver." (https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#example-extensions-testing-workflow) Is this something that I'm expected to run, or will QA run it? (cc @SoftVision-CosminMuntean )
> 
> > Extension does not cause significant[1] performance regressions.
> 
>     1. I see: https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#testing-extensions step 2 - do I run this locally or does QA / something else run this on a standardized machine?
> 
>     2. Are there any other performance tests to run?

We can do this via the tryserver, and I can run these for you.

> 
> 
> > Additional reviews
> 
>     * You scrubbed out "The extension makes use of third party libraries and/or services." but this code brings in code from ublock - just checking that we're good on this one

Oh that was my mistake. I know the license allows it, but have there been any legal concerns? Have we reached out to the author?

> 
>     * "The extension modifies web page content in any way." I believe we should be good on this. Although the treatmentScript branch modifies web page content it does so in a middle ground between current default - fingerprinting protection off, and current option - fingeprinting protection on which blocks at the whole domain level. The treatmentScript branch aims to only block fingerprinting scripts from fingerprinting domains. It has been restricted to only be content that would be blocked by flipping the fingerprinting pref.

Oh hm that's really interesting... I am happy to scrub that one too. Thanks!

**Comment by birdsarah** [comment] 2019-12-04 19:17
One note about performance testing in treatmentScript branch. The way the addon works, it's slower on first load where the filter list gets built than on subsequent loads when the cached list is merely restored. It would be good to take that into account if we need to.

**Comment by biancadanforth** [comment] 2019-12-05 00:03
> Studies don't appear in about:addons anymore and if you don't have icons exposed in Firefox (toolbar etc) then this probably isn't important. I don't think the icons appear in about:studies, @biancadanforth am I missing anything?

Ah that's a good point. Hm... but do active studies show up in `about:debugging`? I asked in `#remote-debugging` in slack. Even if they do, we probably don't need to worry about it.

**Comment by birdsarah** [comment] 2019-12-05 00:40
I have made the easy amendments:
* link out in README - I went with bugzilla as it's public and it links to experimenter
* homepage_url
* strict_min_version

I decided against a strict_max_version. This study is primarily targeting 71. So I want everything up to 72, but I'm not sure how to predict what the final 71.x version will be in case of hotfixes etc.

**Comment by mlopatka** [comment] 2019-12-05 00:45
Likewise, this is a retention study and not showing up in about:addons. I can't think of any reason or place to include an icon. 

> ... Even if they do, we probably don't need to worry about it.

Are we fine to assume an icon is not necessary for this study?

**Comment by rhelmer** [comment] 2019-12-06 00:18
Here are the test runs:
control: https://treeherder.mozilla.org/#/jobs?repo=try&revision=70252c56e2388565508b68c5a13fc55b65494345&selectedJob=279863753

script treatment: https://treeherder.mozilla.org/#/jobs?repo=try&revision=e3c71defd09f39338d303c38a982f1c83058601c&selectedJob=279867683

domain treatment: https://treeherder.mozilla.org/#/jobs?repo=try&revision=b46ffacf23732b0c0db4c6811465816e96d1d7e6

You have to drill down through the "treeherder" menu in the upper-left to get to the "perfherder" dashboard, just eyeballing it looks reasonable. There's some overhead to loading extensions at startup, so comparing the control vs. treatment runs is probably the fairest (I did this and the "compare" feature didn't show anything significant, but it's hard to permalink things from perfherder :/)

**Comment by rhelmer** [comment] 2019-12-06 00:20
BTW I don't think running the normal Firefox unit tests is valuable, it takes a lot of time to dig through intermittent and misleading test results, and this extension isn't loading much privileged code.

**Comment by birdsarah** [comment] 2019-12-06 17:15
We have heard back from @gorhill (ublock origin author) who kindly took a look at the code and noticed a problem (opened as #21).

**Comment by biancadanforth** [comment] 2019-12-10 22:33
> Are we fine to assume an icon is not necessary for this study?

Yes; it took me a while to confirm to my satisfaction, but as long as the `manifest.json` contains `hidden: true`, and the extension is signed with a privileged key, it will neither be listed in `about:addons` nor `about:debugging` by default. You can see some discussion of this [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1602543) in case you're curious.

@rhelmer , would you mind removing the `icon` item and adding the `hidden: true` item to the checklist under `manifest.json`?

**Comment by birdsarah** [comment] 2020-04-24 18:20
Resolved. Study completed.

**Closed as completed by birdsarah** 2020-04-24 18:20 UTC
